version: '3.3'

volumes:
  pg_data:
  static_backend:
  static_frontend:
  media:
  docs:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    build:
      context: ../backend/foodgram
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static_backend:/app/backend_static
      - media:/app/media
      - docs:/app/docs
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static_frontend:/app/result_build
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
  # nginx:
  #   image: nginx:1.19.3
    ports:
      - "8800:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_backend:/static/
      - static_frontend:/static/build/
      - media:/media
      - docs:/usr/share/nginx/html/api/docs
    depends_on:
      - backend
      - frontend
